{% set name = "datascience" %}
{% set version = "0.17.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datascience-{{ version }}.tar.gz
  sha256: 5911f3f3e7c6fb71a2a6c3330170b70d318db012ca3f6c17313bf589624801dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest
    - pip
  run:
    - python >=3.6
    - folium >=0.9.1
    - setuptools
    - matplotlib-base >=3.0.0
    - pandas
    - scipy
    - numpy
    - ipython
    - plotly
    - branca

test:
  imports:
    - datascience
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-8/datascience
  summary: A Jupyter notebook Python library for introductory data science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
